# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cW4dpg7H4M8VJAa7ff4kNz80rnwEcct9
"""

import pandas as pd
import matplotlib.pyplot as plt

# 데이터 준비
data = {
    'Task': ['Task 1', 'Task 2'],
    'Start Date': ['2023-01-01', '2023-01-03'],
    'End Date': ['2023-01-05', '2023-01-10'],
    'Duration': [5, 7]
}

df = pd.DataFrame(data)
df['Start Date'] = pd.to_datetime(df['Start Date'])
df['End Date'] = pd.to_datetime(df['End Date'])

# 간트 차트 생성
plt.figure(figsize=(10, 2))
plt.barh(df['Task'], (df['End Date'] - df['Start Date']).dt.days, left=df['Start Date'].apply(lambda x: x.toordinal()))
plt.xlabel('Date')
plt.ylabel('Task')
plt.title('Gantt Chart')
plt.yticks(df['Task'], df['Task'])
plt.grid(True)

# x축 날짜 레이블 설정
ax = plt.gca()
ax.set_xticks(pd.date_range(start=df['Start Date'].min(), end=df['End Date'].max()).map(lambda x: x.toordinal()))
ax.set_xticklabels(pd.date_range(start=df['Start Date'].min(), end=df['End Date'].max()).strftime("%Y-%m-%d"), rotation=45)

plt.show()

import networkx as nx
import matplotlib.pyplot as plt

# 그래프 생성
G = nx.DiGraph()

# 노드 추가
G.add_edges_from([
    ("Version 1.0", "Feature A"),
    ("Feature A", "Update B"),
    ("Update B", "Fix C"),
    ("Version 2.0", "Feature D"),
    ("Feature D", "Fix E")
])

# 그래프 시각화
pos = nx.spring_layout(G)
nx.draw(G, pos, with_labels=True, node_color='lightblue', node_size=2000, font_size=10, font_weight='bold', arrows=True)

# 그래프 제목 추가
plt.title('Version Control Visualization')
plt.show()

import networkx as nx
import matplotlib.pyplot as plt

# 그래프 생성
G = nx.DiGraph()

# 노드 추가
G.add_edges_from([
    ("Version 1.0", "Feature A"),
    ("Feature A", "Update B"),
    ("Update B", "Fix C"),
    ("Version 2.0", "Feature D"),
    ("Feature D", "Fix E")
])

# 그래프 시각화
pos = nx.spring_layout(G)
nx.draw(G, pos, with_labels=True, node_color='lightblue', node_size=2000, font_size=10, font_weight='bold', arrows=True)

# 그래프 제목 추가
plt.title('Version Control Visualization')
plt.show()