# -*- coding: utf-8 -*-
"""혼자 예제 푸는 노트.ipynb의 사본의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gdROamPyBzdnmaM8j7m-KZIUYoNP_d5y
"""

total_num=0
i=1
while i<10:
  total_num+=i
  i+=1
  print(total_num)

list1=list(range(1,10,2))
print(list1)

sum=0
for each_num in list1:
  sum+=each_num
  print(sum)

lunch_list = ['국밥', '돈까스', '김치찌개', '쌀국수', '햄버거']
for menu in lunch_list:
  print(menu)

lunch_list = ['국밥', '돈까스', '김치찌개', '쌀국수', '햄버거']
index=0
while index<len(lunch_list):
    print(lunch_list[index])
    index+=1

first=2
while first<=9:
  print("<",first,"단>")

  second=1
  while second<=9:
    print(first,"x",second,"=",first*second)
    second= second+1
  print("__________")
  first=first+1

dan = 2   # 2단부터 시작

while dan <= 9:   # 9단까지 반복
    print("<", dan, "단 >")   # 단 제목 출력

    i = 1   # 1부터 9까지 곱하기
    while i <= 9:
        print(dan, "x", i, "=", dan * i)
        i = i + 1   # i를 1씩 증가시킴

    print()   # 한 단 끝나면 줄 띄우기
    dan = dan + 1   # 다음 단으로 넘어가기

for i in range(2, 10):  # 2단부터 9단까지
    print("<", i, "단>")
    for j in range(1, 10):
        print(i, "x", j, "=", i * j)
    print("________")

name = input("이름을 입력하세요:")
print("사랑해요", name, "님!")

num=int(input("숫자를 입력하세요:"))
total = 0
for i in range(1,num+1):
  total+=i

print(total) #total에 "하면" total이라는 글자가 나옴 그래서 "없애줘야 합이 나와"

numbers=input()
num_list=numbers.split() #띄어쓰기로 인식하라는거
num_list=[int(x) for x in num_list]
average = sum(num_list)/len(num_list)
print("입력한 숫자들:", num_list)
print("평균은", average, "입니다")

numbers=[1, 2, 3, 4, 5]
squares=[each_num**2 for each_num in numbers]
print(squares)

user_id = input("아이디를 입력하세요:")
if user_id.isdigit():
  print("해당 아이디는 숫자로만 이루어져 있습니다.")
else:
  print("해당 아이디에는 숫자 이외의 문자가 포함되어있습니다.")

total=0
for i in range(1,101):
  if i % 5 == 0:
      total += i
print(total)

list_1 = ['a','b','c','d']
list_2 = list(range(0,4,1))

for alphabet in list_1:
    for index in list_2:
        print(index, alphabet)

bread=['허니오트', '하티', '위트', '플렛브레드']
meat=['소고기', '닭가슴살', '돼지고기', '칠면조', '참치', '햄']
vegetable=['양상추', '양파', '토마토', '오이']
sauce=['렌치', '스위트어니언', '핫칠리']
cheese=['아메리칸치즈', '슈레드치즈']

for bread_type in bread:
  for meat_type in meat:
    for vegetable_type in vegetable:
      for sauce_type in sauce:
        for cheese_type in cheese:
          print(bread_type, meat_type, vegetable_type, sauce_type, cheese_type)

new_jeans = ['민지', '해린', '혜인', '하니', '다니엘']
for i in range(len(new_jeans)):
  for j in range(i+1, len(new_jeans)):
    print(new_jeans[i],'-',new_jeans[j])

h=173
w=65
appropriate_weight=(h-100)*0.9
if appropriate_weight<w:
  print('과체중')
elif appropriate_weight>w:
  print('저체중')
else:
  print('정상')

w=
if w<=57:
  print('플라이급')
elif w<=61.2:
  print('벤텀급')
elif w<=65.8:
  print('페더급')
elif w<=70.3:
  print('라이트급')
elif w<=77.1:
  print('웰터급')
elif w<=83.9:
  print('미들급')
elif w<=93:
  print('라이트헤비급')
elif w<=120.2:
  print('헤비급')

list_1=list(range(1,100,1))
for each_num in list_1:
  if each_num%2==0:
    print(each_num,'짝수입니다')
  else:
    print(each_num,'홀수입니다')

fruits=['딸기','포도']
input_fruits=input()
if input_fruits in fruits:
  print("해당과일이 있습니다.")
else:
  print("해당과일이 없습니다")

num_list1=[-1,1,0,3,5,10,12,16,25,-48,6,98,100,-99,-67,46,33,-7]
for each_num in num_list1:
  if each_num<0:
    print("음수입니다")
  elif each_num==0:
    print("0")
  else:
    print("양수입니다")

numbers=[3, 8, 15, 22, 7, 10, 14, 9, 6, 2]
even_numbers=[num for num in numbers if num%2==0]
print(even_numbers)

numbers=[3, 8, 15, 22, 7, 10, 14, 9, 6, 2]
for each_num in numbers:
  if each_num%2==0:
    print(each_num)

list_1=[40,100,76]
list_2=[17,56,98]
list_3=[88,59,99]
total_score=list_1+list_2+list_3
print(total_score)

sum=0
for each_num in total_score:
  sum+=each_num
  average=sum/len(total_score)
  print(average)

list_1 = ['a','b','c','d']
list_2 = list(range(0,4,1))

for alphabet in list_1:
    for index in list_2:
        print(index, alphabet)

for odd_num in range(1,10,1):
    print(odd_num)

lunch_list = ['국밥', '돈까스', '김치찌개', '쌀국수', '햄버거']
for menu in lunch_list:
  print(menu)

lunch_list = ['국밥', '돈까스', '김치찌개', '쌀국수', '햄버거']
index=0
while index<len(lunch_list):
  print(lunch_list[index])
  index+=1

dan=2
while dan<=9:
  print('<', dan, "단>")

  second=1
  while second<=9:
    print(dan, "x", second, "=", dan*second)
    second=second+1
  print("ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ")
  dan=dan+1

for i in range(2,10):
  print("<", i, "단>")
  for j in range(1,10):
    print(i, "x", j, "=", i*j)

num=int(input("숫자를 입력하세요"))
total=0
for i in range(1,num+1):
  total+=i
print(total)

numbers=input()
num_list=numbers.split() #띄어쓰기로 인식하라는거
num_list=[int(x) for x in num_list]
average = sum(num_list)/len(num_list)
print("입력한 숫자들:", num_list)
print("평균은", average, "입니다")

numbers=[1,2,3,4,5]
squares=[num**2 for num in numbers]
print(squares)

id_list=input("id를 입력하세요:")
if id_list.isdigit():
  print("해당 아이디는 숫자로만 이루어져 있습니다.")
else:
  print("해당 아이디는 문자가 포함되어 있습니다.")

bread=['허니오트', '하티', '위트', '플렛브레드']
meat=['소고기', '닭가슴살', '돼지고기', '칠면조', '참치', '햄']
vegetable=['양상추', '양파', '토마토', '오이']
sauce=['렌치', '스위트어니언', '핫칠리']
cheese=['아메리칸치즈', '슈레드치즈']
for b in bread:
  for m in meat:
    for v in vegetable:
      for s in sauce:
        for c in cheese:
          print(b,m,v,s,c)

sum=0
for i in range(1,101):
  if i%5==0:
    sum+=i
print(sum)

new_jeans = ['민지', '해린', '혜인', '하니', '다니엘']
for i in range(len(new_jeans)):
  for j in range(i+1, len(new_jeans)):
    print(new_jeans[i],'-',new_jeans[j])

item_list=dict_2.items()
print(item_list)

europe= { 'France': 'Paris','Germany': 'Berlin', 'Italy': 'Rome'}

asia = {'South Korea': 'Seoul', 'Japan': 'Tokyo','China': 'Beijing'}

america= {'United States': 'Washington, D.C.','Canada': 'Ottawa', 'Brazil': 'Brasília'}

list(asia.values())

for k,v in europe.items():
  print(k,v)
for k,v in asia.items():
  print(k,v)
for k,v in america.items():
  print(k,v)

del europe['France']
del asia['China']
del america['Brazil']
print(europe)

europe['spain']='barcelona'
print(europe)

inventory = {
    'gold' : 500,
    'pouch' : ['flint', 'twine', 'gemstone'],
    'backpack' : ['xylophone', 'dagger', 'bedroll', 'bread loaf']}

inventory['burlap bag'] = ['apple', 'small ruby', 'three-toed sloth']
inventory['pouch'].sort()

inventory['pocket']=['seashell', 'strange berry', 'lint']
print(inventory)

print(inventory['backpack'])

inventory['gold']=500+50
print(inventory['gold'])

maria={'korean':94,'english':91,'mathmatics':89,'science':83}
sum=0
marias=maria.values()

for subject, score in maria.items():
  print(subject,":", score)
  print("_______________________")
  sum+=score
  average=sum/len(marias)

print("평균은", average)

def appropriate_calc(height,weight):
  appropriate_weight=(height-100)*0.9
  min_weight = appropriate_weight - 3
  max_weight = appropriate_weight + 3
  print("적정 체중은", min_weight,"~", max_weight, "kg 입니다.")
  return [min_weight,max_weight]
result= appropriate_calc(180,60)
print(result)

library={}
def add_book(title,author):
  if title in library:
    print("등록된 책 입니다")
  else:
    library[title]=author
    print("책이 등록되었습니다")
def search_book(title):
  if title in library:
    print(title, ":", library[title])
  else:
    print("등록된 책이 아닙니다")
add_book('파이썬프로그래밍', '염재선')
add_book('데이터베이스 시스템', '김영희')
add_book('빅데이터 분석론' , '이태섭')

search_book('파이썬프로그래밍')
search_book('파이썬')

sum=0
def add_item(product, price, quantity):

chulsu_score = {'선형대수':50, '기초 프로그래밍':70,
'데이터베이스':80, '텍스트 마이닝':20, '비즈니스 분석론':90}
total_score=0
for k,v in chulsu_score.items():
  total_score+=v
  average=total_score/len(chulsu_score)
print(average)

numbers=5
if numbers%2==0:
  print('짝수')
else:
  print('홀수')

a=[1,7,8,1,10]
a.sort()
print(a)

a=a+[5,6,76]
a.insert(1,48)
print(a)

dict_1 = {'A':90, 'B':80, 'C':70}
for k,v in dict_1.items():
  print(k,v)

dict_1['B']
dict_1['C']=100
print(dict_1)

def check_covid(person):

    if  (person['fever']>37)&(person['breath_interval']<1)&(person['caugh']==1):
      return 1
    else:
      return 0
person_1 = {'fever': 38,  'breath_interval' : 0.5,  'caugh': 1}
person_2 = {'fever': 36.5,  'breath_interval' : 1,  'caugh': 1}
person_3 = {'fever': 37,  'breath_interval' : 2,  'caugh': 0}
print(check_covid(person_1))
print(check_covid(person_2))
print(check_covid(person_3))

lunch_list = ['국밥', '돈까스', '김치찌개', '쌀국수', '햄버거']
index=0
while index<len(lunch_list):
  print(lunch_list[index])
  index+=1

for each_element in lunch_list:
  print(each_element)

first=2
while first<=9:
  print('<', first, '단>')

  second=1
  while second<=9:
    print(first, 'x', second, '=', first*second)
    second=second+1
  print('ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ')
  first=first+1

for f in range(2,10):
  print('<',f ,'단>')
  for s in range(1,10):
    print(f, 'x', s, '=', f*s)

num=int(input("숫자를 입력하세요"))
total=0
for i in range(1,num+1):
  total+=i
  print(total)